name: Sync Lofi Media to R2

on:
  push:
    branches:
      - main
    paths:
      - 'public/media/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync Media Folder
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: "markc-assets"
          source-dir: "public/media"
          destination-dir: "lofi-station"
          keep-file-fresh: true
